local LPlayer = {
	CurrentTool = nil,
	Character = game.Players.LocalPlayer.Character,
}

local function rep()
	-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

	local ohString1 = "rep"

	game:GetService("Players").LocalPlayer.muscleEvent:FireServer(ohString1)
end

local function equiptool(tool)
	for i,v in pairs(game.Players.LocalPlayer.Backpack) do
		if v.Name == LPlayer.CurrentTool.Name then
			v.Parent = LPlayer.Character
		end
	end
end

local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()

local Window = Library.CreateLib("Sleepy Hub", "DarkTheme")



local PlayerTab = Window:NewTab('Player')
local SettingsTab = Window:NewTab("Settings")






local PlayerSection = PlayerTab:NewSection('Player')
local SettingsSection = SettingsTab:NewSection('KeyBinds')












SettingsSection:NewKeybind("Toggle Gui", "Toggles the gui", Enum.KeyCode.RightControl, function()
	Library:ToggleUI()
end)


local test = false

PlayerSection:NewToggle('Auto Rep','',function(Testing)
    
    test = Testing
    
    if test == true then
		local CurrentTool = game.Players.LocalPlayer.Character:FindFirstChildWhichIsA("Tool");
        
        repeat wait()            
            
				for i,v in pairs(game.Players.LocalPlayer.Backpack:GetChildren()) do
					if v.Name == CurrentTool.Name then
						v.Parent = game.Players.LocalPlayer.Character
					end
				end
				for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do
					if v:IsA("Tool") and v.Name ~= CurrentTool.Name then
						v.Parent = game.Players.LocalPlayer.Backpack
					end
				end
				rep();
				
            until test == false
        
        end
    
    
 end)

 local test = false

PlayerSection:NewToggle('Auto Rebirth','',function(Testing)
    
    test = Testing
    
    if test == true then
		local CurrentTool = game.Players.LocalPlayer.Character:FindFirstChildWhichIsA("Tool");
        
        repeat wait()            

				local ohString1 = "rebirthRequest"

				game:GetService("ReplicatedStorage").rEvents.rebirthRemote:InvokeServer(ohString1)
				
				
            until test == false
        
        end
    
    
 end)


 local test = false

 PlayerSection:NewToggle('Inf gems (wait until battle)','',function(Testing)
	 
	 test = Testing
	 
	 if test == true then
			_G.LastGemGlitchPos = game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame
		 repeat wait()            
				if test == true then
					getgenv().InfGemFight = true
				end
			 until test == false
			 getgenv().InfGemFight = false
		 end
	 
	 
  end)
 game:GetService("RunService").Heartbeat:Connect(function()
	if getgenv().InfGemFight == true then
		for i = 1,10 do
			game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame = _G.LastGemGlitchPos
			local ohString1 = "joinBrawl"
	
			game:GetService("ReplicatedStorage").rEvents.brawlEvent:FireServer(ohString1)			
		end

	end
 end)



 -- Pet glitch 
game:GetService("RunService").Heartbeat:Connect(function()
	if _G.AutoPetGlitch == true then
		for i,v in pairs(game.Players.LocalPlayer.Character:GetChildren()) do
			if v:IsA("Tool") then
				v.Parent = game.Players.LocalPlayer.Backpack
			end
		end
		-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

		local ohString1 = "joinBrawl"

		game:GetService("ReplicatedStorage").rEvents.brawlEvent:FireServer(ohString1)
		local VirtualInputManager = game:GetService('VirtualInputManager')
		VirtualInputManager:SendKeyEvent(true, "W", false, game)
		VirtualInputManager:SendKeyEvent(false, "S", false, game)
		game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame = CFrame.new(-230.14520263671875, 11.85832405090332, -92.76506042480469)
		wait()
		workspace.CurrentCamera.CameraType = Enum.CameraType.Fixed
	end
end)

 local test = false

PlayerSection:NewToggle('Auto pet glitch needs to be at 5 xp ','',function(Testing)
    
    test = Testing
    
    if test == true then
		_G.AutoPetGlitch = true
	elseif test == false then
		workspace.CurrentCamera.CameraType = Enum.CameraType.Custom
		_G.AutoPetGlitch = false
		wait()
		local VirtualInputManager = game:GetService("VirtualInputManager")
		VirtualInputManager:SendKeyEvent(false, "W", false, game)
		workspace.CurrentCamera.CameraType = Enum.CameraType.Custom
	end
end)